# REPTE1 ORDRES

# Utilitzacio d'un imatge Debian com a base:
FROM debian
LABEL subject="Repte 1"
LABEL author="@edt ASIX M14"

# Actualitza els repositoris i instal·la els paquets necessaris:
RUN apt-get update && apt-get install -y \ 
 procps iputils-ping iproute2 nmap tree vim 
CMD /bin/bash
