# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "debian_libvirtd" do |debian_libvirtd|
      debian_libvirtd.vm.box = "debian/bullseye64"
      debian_libvirtd.vm.provider "libvirt" do |libvirt|
      end
    end
  
    config.vm.define "debian_virtualbox" do |debian_virtualbox|
      debian_virtualbox.vm.box = "debian/bullseye64"
      debian_virtualbox.vm.provider "virtualbox" do |v|
      end
    end
  end
  