# REPTE3 PSQL

# Utilització d'un imatge PSQL:
FROM postgres

# Copiem el nostra arxiu sql amb totes les dades a la carpeta on s'executaren els scripts que inicialitzaran tot:
COPY training.sql /docker-entrypoint-initdb.d/

